### PR TITLE
Better link styling

### LINKED ISSUE #457: ux: "active" link indicator in the sidenav for the manual
A page on the manual

Adding a distinction between an active and a normal link in the sidenav would greatly improve the UX

Because i'm often trying to CTRL+F to find where I was in the sidenav, little details you know !

### PR DESCRIPTION
**Pull request by buckle2000**
image
Now it looks like this. Fixed visibility issues.

(doesn't fix #457)

### CODE REVIEW

**Comment by lucacasonato** [comment]
I don't know about others, but I like the current styling better. Might just be me though.

**Comment by kennanseno** [comment]
> I don't know about others, but I like the current styling better. Might just be me though.

Prefer the current one as well actually, keeping it black feels better overall as it aligns with the overall theme of the website. I think the highlight to blue if it's the active page suffiices.

**Comment by buckle2000** [comment]
I don't know about "look", but the current contrast on hover is not enough. Also, there is no indication of which pages you have visited, it would be hard for users to remember.

**Comment by buckle2000** [comment]
We con try inverted colors too.

**Comment by lucacasonato** [comment]
What about underline on hover or focus in addition to the slight change of color we have right now, and no indication of what pages you visited? Most pages don't give an indication of that anyway.

**Comment by buckle2000** [comment]
underline + color change is ok. I still think visited links should change color to help with remembering which pages you have visited. It is the default style of `<a>`. Wikipedia has it.  Google used to have that feature (now it opens in new tab). Most sites don't have feature that because it is extra code.

**Comment by ry** [comment]
Thanks for the patch, but it must be green to be considered. Due to the high volume, I'm not reviewing red PRs, just closing to clear out the queue. I apologize if I haven't addressed something. Please open a new PR.

**Pull request closed without merging**
