### PR TITLE
Add Apex Logs API client to the database

### PR DESCRIPTION
**Pull request by tj**

### CODE REVIEW

**Comment by tj** [comment]
hmm I ran the formatter, we have to manually sort the database JSON?

**Comment by tj** [comment]
Gotcha thanks man!

**Comment by tj** [comment]
It would be nice to support `github.com/user/repo` instead of fighting over names in here, more like in Go:

```
import { Client } from 'https://github.com/apex/logs-js/client.ts'
``

**Comment by crowlKats** [comment]
@tj you can import from github directly. with:
https://raw.githubusercontent.com/apex/logs-js/master/client.ts

**Pull request merged**
