### PR TITLE
Auto-focus Third Party Modules search field

### PR DESCRIPTION
**Pull request by chances**
Add the [`autoFocus`](https://material-ui.com/api/text-field/#props) attribute to the Third Party Modules search field for better ergonomics when navigating directly to [deno.land/x](https://deno.land/x).

Related to #176.

### CODE REVIEW

**Comment by lucacasonato** [comment]
This is bad for mobile: https://github.com/denoland/deno_website2/pull/177#issuecomment-572389693, https://github.com/denoland/deno_website2/pull/198

**Comment by chances** [comment]
I can only reproduce the "bad" behavior described in [#177 (comment)](https://github.com/denoland/deno_website2/pull/177#issuecomment-572389693) in the iPhone Simulator (iPhone 8, iOS 13). The keyboard is _not_ shown in Chrome on my Pixel 3a device, nor in the Simulator (iPhone 11, iOS 13).

To mitigate the issue can we consider moving the search field farther above the fold? Like immediately below the "Third Party Modules" header? What about only enabling `autoFocus` on desktops?

**Comment by lucacasonato** [comment]
It does a really obnoxious zoom + scroll on iOS. Desktop only should be fine though.

**Comment by ry** [comment]
Closing because stale and @lucacasonato had issues with it. We appreciate the effort @chances but closing without merge.

**Pull request closed without merging**
