### PR TITLE
Add publish a module button in /x/ page

### LINKED ISSUE #1784: Above the fold action to publish module on deno.land/x

### PR DESCRIPTION
**Pull request by kt3k**
Added 'Publish a module' button in the first view of /x/ page. (It has the same function as 'Add a module' button below)

closes #1784 

スクリーンショット 2021-06-29 18 52 23

### CODE REVIEW

**Comment by lucacasonato** [comment]
Maybe it could be placed on the right of the search bar? 3-4/5 search bar 1-2/5th publish button. I don't like that position for the button.

**Comment by kt3k** [comment]
Moved it to the next of search input.

スクリーンショット 2021-06-29 22 37 36

**Comment by ry** [comment]
I think the button next to search bar is confusing - it makes it seem like the button acts on the text input.

**Comment by lucacasonato** [comment]
Ok, then maybe move it under the `Learn more` and the search bar, and not between the paragraph and the `Learn more`?

**Comment by kt3k** [comment]
Updated to this

スクリーンショット 2021-06-29 22 54 50

**Comment by lucacasonato** [comment]
Can you add like 2-4 more units of spacing above the button? LGTM then.

**Review by lucacasonato — APPROVED** [review]
LGTM. Thanks for enduring my comment!

**Pull request merged**
