### PR TITLE
Add new rupiah module to database.json

### PR DESCRIPTION
**Pull request by andriawan**
I try to add my own simple module to database list

detail repo https://github.com/andriawan/rupiah_ts

### CODE REVIEW

**Comment by lucacasonato** [comment]
The directory listing should be sorted alphabetically. Please insert your entry in the correct location.

**Comment by andriawan** [comment]
> The database entries should be sorted alphabetically. Please insert your entry in the correct location.

I think i have palced my module in the correct order @lucacasonato

**Comment by bartlomieju** [comment]
Hi @andriawan; can you update your PR to latest `master`? There should be no lines removed

**Comment by andriawan** [comment]
> Hi @andriawan; can you update your PR to latest `master`? There should be no lines removed

i have updated my PR to the latest master branch @bartlomieju. please review this

**Pull request merged**
