### PR TITLE
Add color-deno module

### PR DESCRIPTION
**Pull request by selvakumardhivakar**
Vuelancer created color-deno module for printing colored log in console for deno

### CODE REVIEW

**Comment by AvnerCohen** [comment]
Deno has colors in the std lib:  https://github.com/denoland/deno/blob/master/std/fmt/colors.ts

**Comment by selvakumardhivakar** [comment]
**colorlog** using only green, red, yellow colors for indicating success, error and warning.

**Comment by selvakumardhivakar** [comment]
> Deno has colors in the std lib: https://github.com/denoland/deno/blob/master/std/fmt/colors.ts

Now only I noticed the standard library for colors in deno. 
> I think this _colorlog_ will be used only for indicating success, error and warning.

**Comment by rjoydip** [comment]
@selvakumardhivakar `colorlog` looks like a very simple utility it could be achieve through deno colors std modules. But if you could extends `colorlog` functionality more like [signale](https://github.com/klaussinani/signale) modules do in node.

**Pull request merged**
