### PR TITLE
Revert "Eyecandy: Longer transitions"

### PR DESCRIPTION
**Pull request by lucacasonato**
Reverts denoland/deno_website2#1780

@Milo123459 Thanks for the PR, but I think this makes the whole site feel slower. I am going to revert it.

### CODE REVIEW

**Comment by wperron** [comment]
> I think this makes the whole site feel slower.

I think this is a bit harsh, the patch literally just changes the duration of the animation on-hover for a couple of clickable items

**Comment by lucacasonato** [comment]
That's the power of UI! Even minuscule changes can make or break it. I think it makes the experience of navigating around the site worse 🤷‍♂️

**Comment by lucacasonato** [comment]
@Milo123459 No worries. Nothing against you personally!

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
