### PR TITLE
Add types for database

### PR DESCRIPTION
**Pull request by parzhitsky**
Add type-safety and IntelliSense (editor suggestions) to database file

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
I don't know if this is a great idea, other projects may also rely upon the `database.json` file (like ours does) which this PR would break. I personally think it's much easier to consume JSON than an object in many use cases... :(

**Comment by parzhitsky** [comment]
The fact that this is a breaking change is actually my biggest concern. Would you mind jotting about how exactly your project uses the json? Perhaps, it might be fixed by dynamically generating files at some point, or something like that (or something completely different 🙂).

As for ease of use, I tend to disagree, since a) with importing (or otherwise incorporating) the file you import both value (i.e., JavaScript implementation) _and_ types in one go; b) there's no need to parse/stringify anything, as some systems require; c) third-party contributions to that file are validated earlier; and so on.

**Comment by AnandChowdhary** [comment]
We have a deno.land/x mirror that fetches each package from `database.json` here: https://github.com/denorg/x.

It's trivial for me to change the download script to support the `package.ts` file, but my general idea is that JSON is more universal, better-supported in other contexts (non-JavaScript scripts, for example), and better-understood by computers that don't use IntelliSense.

**Comment by AnandChowdhary** [comment]
But I think this might become moot as Deno's package registry evolves and doesn't have a `database.json` anymore: https://github.com/denoland/deno_website2/issues/406

**Comment by parzhitsky** [comment]
Ooo, I’m glad they’re thinking this through! The whole approach with npm-ish global scope of unique names updated manually through pull requests seamed flawed from the start.

Thanks for the link!

**Comment by lucacasonato** [comment]
I think JSON is better suited here and there are very valid usecases for importing this json file externally. I think keeping it as JSON makes more sense because it is more accessible. We have tests to catch style errors in the database anyway.

**Comment by ry** [comment]
I appreciate the patch, but JSON for data seems more versatile to me.

**Pull request closed without merging**
