### PR TITLE
Add package: TeddyTags

### PR DESCRIPTION
**Pull request by obnoxiousnerd**

### CODE REVIEW

**Comment by bartlomieju** [comment]
@obnoxiousnerd  please merge with master

**Comment by obnoxiousnerd** [comment]
@bartlomieju can't merge; atleast one review is required

**Comment by obnoxiousnerd** [comment]
cc @bartlomieju

**Comment by bartlomieju** [comment]
@obnoxiousnerd You should merge latest `master` into your local branch or open a new PR

**Comment by obnoxiousnerd** [comment]
Error says "Failed during stage 'building site': Deploy directory 'build/' does not exist"

**Comment by obnoxiousnerd** [comment]
@bartlomieju i went through similar PRs but they don't have netlify tests but mine has them. Any reason??

**Comment by bartlomieju** [comment]
You opened a PR before we fixed CI. The simplest solution is to open a new PR

**Comment by obnoxiousnerd** [comment]
Reopening

**Comment by obnoxiousnerd** [comment]
@bartlomieju see #555

**Pull request closed without merging**
