### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by lucacasonato**

### CODE REVIEW

**Review by kt3k — APPROVED** [review]
LGTM 🚀

**Comment by wperron** [comment]
Should probably also deactive the GH workflow step for CF worker since it's always going to fail after this

**Comment by wperron** [comment]
Just did a manual look around on https://deno-website2.deno.dev and haven't found any issues. Will work on converting the Worker tests to Deno before we merge

**Comment by wperron** [comment]
There's a fair bit of difference in the response headers

CloudFlare:
```text
date: Tue, 25 May 2021 13:24:51 GMT
content-type: application/typescript; charset=utf-8
content-length: 278
cf-ray: 654f16204d324bd1-YUL
accept-ranges: bytes
access-control-allow-origin: *
age: 5034
cache-control: public, max-age=31536000, immutable
etag: "c668ccb38a11e98f6c66e0c2ca1f7175"
last-modified: Mon, 17 May 2021 14:44:06 GMT
cf-cache-status: HIT
cf-request-id: 0a454c283200004bd1d218d000000001
x-amz-id-2: smpFoyeSDFXuadbjV88qoLQtZjlhNabqclWImf+hUDQGJUNuHvXG+lKWqdbbIfrQVOm+KAIZ1xI=
x-amz-request-id: 8QNS6JBN222BX7H8
x-amz-version-id: 2uFW5a1hDjuQpilTPksSU7XCecKHe9DY
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
```

Deploy:
```text
access-control-allow-origin: *
x-deno-ray: northamerica-northeast1-b::b83f2e030fe39e3b6a59ab71db8f261d
date: Tue, 25 May 2021 13:25:04 GMT
via: HTTP/1.1 deploy
```

**Comment by lucacasonato** [comment]
Content type missing is definitely a blocker.

**Comment by lucacasonato** [comment]
Content type missing is definitely a blocker.

**Comment by wperron** [comment]
curling S3 returns the headers normally
```text
x-amz-id-2: ddCAGW/GoXNCIvG99ommIG57SSlRlpSIxSfC3M1si07yA5JVz5XFGYmcZ2NKsw2S188AclycNOU=
x-amz-request-id: JM3Y9NJ43ZFVTJTE
Date: Tue, 25 May 2021 15:17:31 GMT
Last-Modified: Sat, 29 Aug 2020 20:02:50 GMT
ETag: "88666d68bbc55eb75a54d596b6de9715"
Cache-Control: public, max-age=31536000, immutable
x-amz-version-id: null
Accept-Ranges: bytes
Content-Type: application/typescript; charset=utf-8
Content-Length: 117
Server: AmazonS3
```
I wonder what changed? maybe the wrangler utility for CF handles response headers differently than Deno? In any case, we can be confident that if it doesn't work in the CLI, it also won't work on Deploy, so I'll just focus on fixing it

**Comment by lucacasonato** [comment]
Culprit is https://github.com/denoland/deno_website2/pull/1761/files#diff-9b2b4d7de4ecbf268fd5abe41f2347e2d15b0b0f30b92a091f84a0d4f7a00a03R88. https://github.com/denoland/deno/issues/10367

**Comment by wperron** [comment]
With the fix:
```
cache-control: public, max-age=31536000, immutable
content-length: 278
content-type: application/typescript; charset=utf-8
date: Tue, 25 May 2021 15:48:59 GMT
etag: "c668ccb38a11e98f6c66e0c2ca1f7175"
last-modified: Mon, 17 May 2021 14:44:06 GMT
server: AmazonS3
x-amz-id-2: ZkkWrRiPphZOYVAOLeTVhtXu9nBa2NbJhRH19F9T8x3k4PR+SmUMrNYuhPQRYwStN39l48n74k4=
x-amz-request-id: E07VN4YR7QHQ26AV
x-amz-version-id: 2uFW5a1hDjuQpilTPksSU7XCecKHe9DY
access-control-allow-origin: *
via: HTTP/1.1 deploy
x-deno-ray: northamerica-northeast1-b::87ae9270fea7b933660140c862a34f21
```

**Comment by wperron** [comment]
Also tested importing into a Deno script, works well :+1:

**Pull request merged**
