### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by mumumilk**
Starts implementation of dark mode on docs as in #409 

routes affected:

/ (index)
   image

/artwork
image

/translations
image

/benchmarks
image

**Other routes such as `x` should not have dark mode.**

I also added an experimental palette called `grey`, so i wont modify light mode palette.

### CODE REVIEW

**Review by sno2 — COMMENTED** [review]
The Cookie Banner could also do with a dark theme.  You probably didn't see it, though, as it stores whether it has been dismissed or not in the `LocalStorage`.  Otherwise, this looks great.

image

**Comment by mumumilk** [comment]
@sno2 i left that white on purpose because on "light mode" it is black, contrasting with the rest of the website.

Should i fix conflicts for this pr? Its just aesthetic so i think its not a priority right now, so maybe we can close it. I'll be happy to help implementing this another time if so.

**Comment by sno2** [comment]
> @sno2 i left that white on purpose because on "light mode" it is black, contrasting with the rest of the website.
> 
> Should i fix conflicts for this pr? Its just aesthetic so i think its not a priority right now, so maybe we can close it. I'll be happy to help implementing this another time if so.

Ahh, good explanation.  I understand.  Per the conflicts, you can fix them if you want, but but it looks like the higher ups aren't looking into this repo that much.

**Comment by ry** [comment]
Hi @mumumilk - I'm going to close this because it's stale and out of date. Thanks for the effort - I apologize that we didn't give any encouraging reviews - it was a good start, just needed more work.
Cheers, Ryan

**Pull request closed without merging**
