### PR TITLE
Add description field to database.json to allow module description

### PR DESCRIPTION
**Pull request by fakoua**
- Add "desc: "..." to database.json to allow module description
- Display the desc field in the RegistryIndex page.

### CODE REVIEW

**Comment by fakoua** [comment]
It was due to conflict between multiple emails of mine, 
CLA signed

**Comment by ry** [comment]
sure - but i don't like the white boxes - can you make the design more minimal?

**Comment by fakoua** [comment]
Sure,
However, should I discuss the features before pull request? 
I can devote some time to the website, any rules or guidelines?

**Comment by fakoua** [comment]
@ry I changed the code according to your comment,
Thanks

**Comment by fakoua** [comment]
@ry , conflict merged.

Thanks

**Pull request merged**
