### PR TITLE
removed non functional(atm) search bar

### PR DESCRIPTION
**Pull request by qadratic**
So I commented out the non functional search bar in Manual.tsx
meanwhile I am working on making a search functionality.

fixed issue: #470

### CODE REVIEW

**Comment by ry** [comment]
cc @lucacasonato What were your plans for the search bar? I actually never noticed it until now.

**Comment by qadratic** [comment]
okay so while typing, search results will be will be displayed on drop-down as suggestions. Each dropdown element will contain a link to that particular heading.

**Comment by lucacasonato** [comment]
> What were your plans for the search bar? I actually never noticed it until now.

@ry Added it in the original design and wanted it to do full manual search, but never actually implemented it and then forgot to remove it again. Algolia DocSearch seems pretty great, maybe we can integrate that? https://docsearch.algolia.com/

**Comment by lucacasonato** [comment]
@ry I guess, but DocSearch is really awesome :-D

**Pull request merged**
