### PR TITLE
added denoenv

### PR DESCRIPTION
**Pull request by rubiin**
Dotenv module port of nodejs dotenv

### CODE REVIEW

**Comment by crowlKats** [comment]
_another one_

**Comment by rubiin** [comment]
> _another one_

I was using yours module earlier but i didnt find an option

**Comment by crowlKats** [comment]
ah i see. you could have just opened an issue, i would have addressed it ASAP

**Comment by rubiin** [comment]
> ah i see. you could have just opened an issue, i would have addressed it ASAP

I will open an issue about it. Seems like it would be very helpful option for your module in the long run

**Pull request merged**
