### PR TITLE
Format the header padding and max width

### PR DESCRIPTION
**Pull request by narwy**
From this:
image

To this:
image

### CODE REVIEW

**Comment by narwy** [comment]
This also fixes the responsiveness issue as well @lucacasonato 

That said I think on the homepage with this change the `max-w-screen-sm` content sections could become `max-w-screen-md` and have a more reading area so they're less compact, opinions?

**Comment by lucacasonato** [comment]
I think the header should only be wider on pages where the content is also wider (registry page). Everywhere else it should be as it is now.

As for generally changing max-w-screen-sm to max-w-screen-md: lets not right now. I need to think about this some more

**Comment by narwy** [comment]
@lucacasonato You happy for a prop to be passed then, `widerContent` boolean? if true uses`max-w-screen-xl` if not defaults to `max-w-screen-lg` ?

**Comment by narwy** [comment]
@lucacasonato over to you mate, added the `widerContent` if passed as true, does what it says on the box

**Pull request merged**
