### PR TITLE
Fixed images path on 404 Not Found Page

### PR DESCRIPTION
**Pull request by eusonlito**

### CODE REVIEW

**Comment by mooxl** [comment]
this got already resolved in #1623

**Comment by kt3k** [comment]
Probably this one should've been merged instead of #1623 (because this is earlier than that). But anyway we already fixed it. Closing.

Thank you for your contribution anyway @eusonlito

**Comment by mooxl** [comment]
Yeah sry for that. When I created the PR I didn't know this one already existed

**Comment by kt3k** [comment]
@mooxl no worries. thank you for your contributions as well :)

**Pull request closed without merging**
