### PR TITLE
Add random_float and random_int to database

### PR DESCRIPTION
**Pull request by yg**
- https://github.com/yg/random-int ported from https://github.com/sindresorhus/random-int
- https://github.com/yg/random-float ported from https://github.com/sindresorhus/random-float

### CODE REVIEW

**Comment by sholladay** [comment]
Sindre's modules already have TS type definitions and are Deno compatible. Why not just add them?

**Comment by yg** [comment]
Nice Idea @sholladay! I haven't tested with deno! I'm going to check now!

**Comment by yg** [comment]
@sholladay I just tested it with this snippet

```ts
import { randomFloat } from "https://raw.githubusercontent.com/sindresorhus/random-float/master/index.d.ts";

console.log(randomFloat(10));
console.log(randomFloat(10, 1000));
```

Getting this error!

```
Compile file:///root/yg/test.ts
error: TS2595 [ERROR]: 'randomFloat' can only be imported by using a default import.
import { randomFloat } from "https://raw.githubusercontent.com/sindresorhus/random-float/master/index.d.ts";
         ~~~~~~~~~~~
    at file:///root/yg/test.ts:1:10

TS2497 [ERROR]: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.
import { randomFloat } from "https://raw.githubusercontent.com/sindresorhus/random-float/master/index.d.ts";
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///root/yg/test.ts:1:29

Found 2 errors.
```

**Comment by sholladay** [comment]
Oh, right. I was thinking they would work because they don't import anything, but of course the export syntax matters, too, and those are still CommonJS. Silly me.

Still, Sindre might be willing to accept a PR to change them to use ES6 export syntax.

**Pull request merged**
