### PR TITLE
Add french to translations.json.

### PR DESCRIPTION
**Pull request by Ayfri**
This adds the french translation that I made.

### CODE REVIEW

**Comment by wperron** [comment]
Couple of comments:
- (homepage) "Consiste en un seul fichier exécutable" I feel like it should be "Publié en un seul fichier exécutable"
- the "Installation" section isn't translated at all
- "Découvrir" for "Getting started" - never seen it put like that, but I like it 🤷 
- "Documentation basique du moteur" -> "Documentation de base du moteur"
- "des détails sur l'implémentation de Deno" -> "des détails sur le fonctionnement interne de Deno"
- The last paragraph of the "Documentation" section as well as the "standard modules" and "third party modules" sections aren't translated
- The benchmarks page isn't translated

**Comment by Ayfri** [comment]
Thanks for the improvements, I don't find the `Documentation basique du moteur` part, where did you see that?

**Comment by wperron** [comment]
In the "Documentation du moteur" section, below "Decouvrir"

as for the other parts, I don't know what to say, I opened on a different browser on a different machine just to be sure and I still see them in english

**Comment by Ayfri** [comment]
@wperron Weird, when I open the website in local using the `dev` script, everything is translated, do I have to run a script to deploy everything?

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
