### PR TITLE
Added hex-functions.

### PR DESCRIPTION
**Pull request by eserozvataf**
Function abstraction for better portability between platforms. Write once, run on cli, bots, function runtimes and web apis.

### CODE REVIEW

**Comment by MrPeker** [comment]
Great project for headache on between different runtime environments, nice work! And cool PR no. 😂

**Comment by eserozvataf** [comment]
Is there a reason why this module is removed from deno.land/x ? Or is it a temporarily issue. /cc @ry

**Comment by lucacasonato** [comment]
You never tagged a release for your module. See https://deno.land/posts/registry2

**Comment by eserozvataf** [comment]
thank you, i've just discovered that.

**Pull request merged**
