### PR TITLE
update the database with new library soxa for deno

### PR DESCRIPTION
**Pull request by fakoua**
https://github.com/fakoua/soxa/blob/master/README.md

### CODE REVIEW

**Comment by ry** [comment]
@axetroy can you explain?

**Comment by axetroy** [comment]
> @axetroy can you explain?

This is not a Deno module

- Not written in Typescript
- No type declaration
- No test cases

It only works on node.js

So I don't think it is suitable for adding to database.json at this time.

**Comment by fakoua** [comment]
Thank you very much,
I will try my best to convert it the code to typescript, it works well with deno, it is a clone of axios with fetch adapter instead of http module.

However, it is missing test cases and typescript support. 

Thanks again.

**Comment by ry** [comment]
@fakoua TS is not required but some tests in deno (maybe even CI) would be good

see this for an example of how to setup ci https://github.com/oakserver/oak/blob/master/.travis.yml

**Comment by fakoua** [comment]
Thank you very much,
One more question, how can I use deno.land/x/.... Before my pack get listed?

**Comment by axetroy** [comment]
> Thank you very much,
> One more question, how can I use deno.land/x/.... Before my pack get listed?

You don't need to import from `deno.land/x/`

You can import from relative path

**Comment by fakoua** [comment]
Thank you all

**Comment by fakoua** [comment]
Hi,
1- I added test cases for most of modules
2- Automated build/test with travis-ci
3- Test the functionality with DENO and removed any node dependencies.
4- Update the README to include more working examples.

Many thanks

**Pull request merged**
