### PR TITLE
Moved to new chart library and readded normalized charts

### PR DESCRIPTION
**Pull request by lucacasonato**
Changed the chart library to  [apexcharts](https://apexcharts.com) - this is a pretty complete library and works way better with React than c3 (discussed in #26).

This adds some nice things: 
- we now have png and svg download buttons on the charts (provided by the apexchart module out of the box)
- way more customization options https://apexcharts.com/docs/options
- better zooming than c3 - only supported on numeric x-axis so we aren't using it right now - I am planning to re add this in a future PR.
- animations if we want them. They seem to slow everything down quite a bit, so I disabled them for now - we can look into that later as well.

I also re added the normalized checkbox and the respective graphs.

### CODE REVIEW

**Comment by lucacasonato** [comment]
The build is failing because of issue described in #41

**Comment by ry** [comment]
@lucacasonato please merge master

**Comment by ry** [comment]
@lucacasonato Looks fresh. Is this ready to land?

**Comment by lucacasonato** [comment]
@ry Sure

**Pull request merged**
