### PR TITLE
feat: add languages page

### PR DESCRIPTION
**Pull request by tokiedokie**
Adds `/translations` page
this page contains links to documentation in other languages

ref: denoland/deno#7490, denoland/deno#5435, denoland/deno#5911, #550

### CODE REVIEW

**Comment by tokiedokie** [comment]
@ry WDYT?

**Comment by ry** [comment]
@tokiedokie Cool - put the link with the other "extra" pages at the bottom. Title it "Translations"?

**Comment by tokiedokie** [comment]
@ry Thank you for your response. I renamed `languages` to `translations`, added link to translations on footer

**Review by ry — APPROVED** [review]
Thank you

**Pull request merged**
