### PR TITLE
Add 3rd party library fp-ts

### PR DESCRIPTION
**Pull request by pe3**
Related issue under gcanti/fp-ts https://github.com/gcanti/fp-ts/issues/1130

### CODE REVIEW

**Comment by pe3** [comment]
Running `yarn test` locally it seems that database names with dashes are not allowed: 

      23 | test("database names with dashes are not allowed", () => {
      24 |   for (const key in DATABASE) {
    > 25 |     expect(key.includes("-")).toBeFalsy();
         |                               ^
      26 |   }
      27 | });
      28 | 

Is there any way for adding fp-ts to the database?

**Comment by pe3** [comment]
I renamed the database entry: fp-ts -> fp_ts

**Comment by pe3** [comment]
I wasn't aware of any method to test it the database entry actually works for Deno CLI so I don't know if it works.

**Comment by tmueller** [comment]
Maybe this should be removed again. Since fp-ts is not a deno module, it won't load.

**Comment by pe3** [comment]
@tmueller it should be removed. I already made a PR for removing it https://github.com/denoland/deno_website2/pull/239

**Pull request merged**
