### PR TITLE
Added readline

### PR DESCRIPTION
**Pull request by vslinko**

### CODE REVIEW

**Comment by lucacasonato** [comment]
@vslinko FYI: https://deno.land/std/io/mod.ts contains this functionality already

**Comment by vslinko** [comment]
@lucacasonato ow, I looked for this function in std/io but somehow I've missed it.

Looks like `readSlice` have significant difference from my module — it expects single byte delimiter. Also `readline` provides simple and pretty API.

**Comment by vslinko** [comment]
I'm going to develop csv reader module based on `readline`.

**Comment by vslinko** [comment]
I think that search for function definitions from `std` and external modules could be convenient for deno.land website.

**Pull request merged**
