### PR TITLE
Port worker typescript to Deno

### PR DESCRIPTION
**Pull request by mrkurt**
This is a start at porting the Deno website to Deno. I ported the worker code over (a) because it was easy and (b) to see if there's any appetite for porting the rest.

One question: Does the app make any use of HTTP caching in Cloud Flare? The port just naively fetches from S3, it's not the fastest, caching is easy (but can happen later).

And a note: I changed this to deploy to [Fly.io](https://fly.io)(which makes sense, since it's where I work). This can be deployed pretty much anywhere Deno is, though.

* https://deno-website.fly.dev/
* https://deno-website-staging.fly.dev/

### CODE REVIEW

**Comment by lucacasonato** [comment]
Hi @mrkurt!

It is awesome that you got started on this. I do have a few concerns though:

> One question: Does the app make any use of HTTP caching in CloudFlare? The port just naively fetches from S3, it's not the fastest, caching is easy (but can happen later).

Yes - we all static files from S3 are cached in CloudFlare. We actually serve all versioned code files with `immutable` cache control headers. In my very preliminary testing this branch is about 3x slower than using the CloudFlare Worker + caching:
```
~ ❯❯❯ hey https://deno.land/std@0.65.0/version.ts

Summary:
  Total:	0.3821 secs
  Slowest:	0.2346 secs
  Fastest:	0.0363 secs
  Average:	0.0851 secs
  Requests/sec:	523.4749

  Total data:	59000 bytes
  Size/request:	295 bytes

Response time histogram:
  0.036 [1]	|
  0.056 [141]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.076 [8]	|■■
  0.096 [0]	|
  0.116 [0]	|
  0.135 [0]	|
  0.155 [0]	|
  0.175 [0]	|
  0.195 [9]	|■■■
  0.215 [27]	|■■■■■■■■
  0.235 [14]	|■■■■


Latency distribution:
  10% in 0.0397 secs
  25% in 0.0419 secs
  50% in 0.0465 secs
  75% in 0.1827 secs
  90% in 0.2083 secs
  95% in 0.2160 secs
  99% in 0.2245 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0355 secs, 0.0363 secs, 0.2346 secs
  DNS-lookup:	0.0123 secs, 0.0000 secs, 0.0503 secs
  req write:	0.0001 secs, 0.0000 secs, 0.0033 secs
  resp wait:	0.0494 secs, 0.0362 secs, 0.0947 secs
  resp read:	0.0001 secs, 0.0000 secs, 0.0009 secs

Status code distribution:
  [200]	200 responses
```

```
~ ❯❯❯ hey https://deno-website-staging.fly.dev/std@0.65.0/version.ts

Summary:
  Total:	1.3565 secs
  Slowest:	0.5869 secs
  Fastest:	0.1192 secs
  Average:	0.2679 secs
  Requests/sec:	147.4388

  Total data:	59000 bytes
  Size/request:	295 bytes

Response time histogram:
  0.119 [1]	|■
  0.166 [19]	|■■■■■■■■■■■■■
  0.213 [49]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.260 [60]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.306 [21]	|■■■■■■■■■■■■■■
  0.353 [1]	|■
  0.400 [17]	|■■■■■■■■■■■
  0.447 [13]	|■■■■■■■■■
  0.493 [16]	|■■■■■■■■■■■
  0.540 [1]	|■
  0.587 [2]	|■


Latency distribution:
  10% in 0.1671 secs
  25% in 0.2030 secs
  50% in 0.2302 secs
  75% in 0.3472 secs
  90% in 0.4433 secs
  95% in 0.4569 secs
  99% in 0.5727 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0317 secs, 0.1192 secs, 0.5869 secs
  DNS-lookup:	0.0004 secs, 0.0000 secs, 0.0024 secs
  req write:	0.0001 secs, 0.0000 secs, 0.0009 secs
  resp wait:	0.2323 secs, 0.1190 secs, 0.4939 secs
  resp read:	0.0039 secs, 0.0000 secs, 0.0482 secs

Status code distribution:
  [200]	200 responses
```

(tested from Frankfurt, Germany)

Using Deno would be really great, but performance needs to be just as good (or at least very close to) what we have now. Also caching is very important, because touching S3 every time will be expensive in the long run. I think these are solvable issues though.

Are you on the Deno Discord (https://discord.gg/deno)? Feel free to reach out to me via DM so we can discuss this :-)

**Comment by mrkurt** [comment]
Yeah I found the cache call shortly after I submitted this! I'll put a basic cache in.

You'll want to use https://deno-website.fly.dev for testing, it's running in a bunch of regions (vs the staging, which is just in one).

**Comment by lucacasonato** [comment]
> You'll want to use https://deno-website.fly.dev for testing, it's running in a bunch of regions (vs the staging, which is just in one).

Ah yes, that improves things a lot already.

```
~ ❯❯❯ hey https://deno-website.fly.dev/std@0.65.0/version.ts

Summary:
  Total:	1.2970 secs
  Slowest:	0.6664 secs
  Fastest:	0.1156 secs
  Average:	0.2220 secs
  Requests/sec:	154.2048

  Total data:	59000 bytes
  Size/request:	295 bytes

Response time histogram:
  0.116 [1]	|■
  0.171 [79]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.226 [48]	|■■■■■■■■■■■■■■■■■■■■■■■■
  0.281 [22]	|■■■■■■■■■■■
  0.336 [6]	|■■■
  0.391 [42]	|■■■■■■■■■■■■■■■■■■■■■
  0.446 [0]	|
  0.501 [0]	|
  0.556 [0]	|
  0.611 [1]	|■
  0.666 [1]	|■


Latency distribution:
  10% in 0.1294 secs
  25% in 0.1408 secs
  50% in 0.1998 secs
  75% in 0.2876 secs
  90% in 0.3702 secs
  95% in 0.3712 secs
  99% in 0.5765 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0142 secs, 0.1156 secs, 0.6664 secs
  DNS-lookup:	0.0003 secs, 0.0000 secs, 0.0016 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0005 secs
  resp wait:	0.1988 secs, 0.1154 secs, 0.5954 secs
  resp read:	0.0089 secs, 0.0000 secs, 0.0530 secs

Status code distribution:
  [200]	200 responses

```

**Comment by mrkurt** [comment]
@lucacasonato There's a cache in place (and tests pass now!). Have a look and see how it works.

**Comment by lucacasonato** [comment]
```
~ ❯❯❯ hey -z 10s -c 10 http://deno.land/std@0.65.0/http/mod.ts

Summary:
  Total:	10.0232 secs
  Slowest:	3.6055 secs
  Fastest:	0.0184 secs
  Average:	0.0333 secs
  Requests/sec:	300.1036
  
  Total data:	276736 bytes
  Size/request:	92 bytes

Response time histogram:
  0.018 [1]	|
  0.377 [2993]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.736 [4]	|
  1.095 [1]	|
  1.453 [8]	|
  1.812 [0]	|
  2.171 [0]	|
  2.529 [0]	|
  2.888 [0]	|
  3.247 [0]	|
  3.605 [1]	|


Latency distribution:
  10% in 0.0217 secs
  25% in 0.0236 secs
  50% in 0.0271 secs
  75% in 0.0310 secs
  90% in 0.0360 secs
  95% in 0.0395 secs
  99% in 0.0526 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0001 secs, 0.0184 secs, 3.6055 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0003 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0001 secs
  resp wait:	0.0210 secs, 0.0107 secs, 1.1541 secs
  resp read:	0.0000 secs, 0.0000 secs, 0.0068 secs

Status code distribution:
  [200]	3008 responses
```
```
~ ❯❯❯ hey -z 10s -c 10 https://deno-website.fly.dev/std@0.65.0/http/mod.ts

Summary:
  Total:	10.0207 secs
  Slowest:	0.6779 secs
  Fastest:	0.0240 secs
  Average:	0.0295 secs
  Requests/sec:	339.1972
  
  Total data:	312708 bytes
  Size/request:	92 bytes

Response time histogram:
  0.024 [1]	|
  0.089 [3387]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.155 [1]	|
  0.220 [0]	|
  0.286 [0]	|
  0.351 [0]	|
  0.416 [0]	|
  0.482 [0]	|
  0.547 [6]	|
  0.613 [3]	|
  0.678 [1]	|


Latency distribution:
  10% in 0.0247 secs
  25% in 0.0250 secs
  50% in 0.0259 secs
  75% in 0.0290 secs
  90% in 0.0333 secs
  95% in 0.0375 secs
  99% in 0.0575 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0005 secs, 0.0240 secs, 0.6779 secs
  DNS-lookup:	0.0001 secs, 0.0000 secs, 0.0351 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0001 secs
  resp wait:	0.0284 secs, 0.0240 secs, 0.4437 secs
  resp read:	0.0001 secs, 0.0000 secs, 0.0462 secs

Status code distribution:
  [200]	3399 responses
```

**Comment by mrkurt** [comment]
One option is to use the Fly Deno app as an origin, if you still want to route through CloudFlare. It's just one more moving piece but there are reasons some people want to!

This tool is pretty handy for testing from different locations, here's a run from three cities in China: https://wheresitup.com/demo/results/5f440d4296f665392e6855d2

**Comment by axetroy** [comment]
> ```
> ~ ❯❯❯ hey -z 10s -c 10 http://deno.land/std@0.65.0/http/mod.ts
> 
> Summary:
>   Total:	10.0232 secs
>   Slowest:	3.6055 secs
>   Fastest:	0.0184 secs
>   Average:	0.0333 secs
>   Requests/sec:	300.1036
>   
>   Total data:	276736 bytes
>   Size/request:	92 bytes
> 
> Response time histogram:
>   0.018 [1]	|
>   0.377 [2993]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
>   0.736 [4]	|
>   1.095 [1]	|
>   1.453 [8]	|
>   1.812 [0]	|
>   2.171 [0]	|
>   2.529 [0]	|
>   2.888 [0]	|
>   3.247 [0]	|
>   3.605 [1]	|
> 
> 
> Latency distribution:
>   10% in 0.0217 secs
>   25% in 0.0236 secs
>   50% in 0.0271 secs
>   75% in 0.0310 secs
>   90% in 0.0360 secs
>   95% in 0.0395 secs
>   99% in 0.0526 secs
> 
> Details (average, fastest, slowest):
>   DNS+dialup:	0.0001 secs, 0.0184 secs, 3.6055 secs
>   DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0003 secs
>   req write:	0.0000 secs, 0.0000 secs, 0.0001 secs
>   resp wait:	0.0210 secs, 0.0107 secs, 1.1541 secs
>   resp read:	0.0000 secs, 0.0000 secs, 0.0068 secs
> 
> Status code distribution:
>   [200]	3008 responses
> ```
> 
> ```
> ~ ❯❯❯ hey -z 10s -c 10 https://deno-website.fly.dev/std@0.65.0/http/mod.ts
> 
> Summary:
>   Total:	10.0207 secs
>   Slowest:	0.6779 secs
>   Fastest:	0.0240 secs
>   Average:	0.0295 secs
>   Requests/sec:	339.1972
>   
>   Total data:	312708 bytes
>   Size/request:	92 bytes
> 
> Response time histogram:
>   0.024 [1]	|
>   0.089 [3387]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
>   0.155 [1]	|
>   0.220 [0]	|
>   0.286 [0]	|
>   0.351 [0]	|
>   0.416 [0]	|
>   0.482 [0]	|
>   0.547 [6]	|
>   0.613 [3]	|
>   0.678 [1]	|
> 
> 
> Latency distribution:
>   10% in 0.0247 secs
>   25% in 0.0250 secs
>   50% in 0.0259 secs
>   75% in 0.0290 secs
>   90% in 0.0333 secs
>   95% in 0.0375 secs
>   99% in 0.0575 secs
> 
> Details (average, fastest, slowest):
>   DNS+dialup:	0.0005 secs, 0.0240 secs, 0.6779 secs
>   DNS-lookup:	0.0001 secs, 0.0000 secs, 0.0351 secs
>   req write:	0.0000 secs, 0.0000 secs, 0.0001 secs
>   resp wait:	0.0284 secs, 0.0240 secs, 0.4437 secs
>   resp read:	0.0001 secs, 0.0000 secs, 0.0462 secs
> 
> Status code distribution:
>   [200]	3399 responses
> ```
> 
> We need some tests from other parts of the world. Especially China. We have had issues with deno.land being unavailable there, and so far cloudflare has solved most of that.
> 
> @axetroy Can you reach [deno-website.fly.dev/std@0.65.0/http/mod.ts](https://deno-website.fly.dev/std@0.65.0/http/mod.ts) from China?

yes. sure.

**Comment by mrkurt** [comment]
Probably safe to close this now. ;)

**Pull request closed without merging**
