### PR TITLE
Added Escapehtml flag to render html

### LINKED ISSUE #20: HTML code showing up between markdown.
Screenshot 2019-10-22 at 2 23 16 PM

@ry, The `prettier` HTML code is being shown between markdown. I was also trying to make the toc but its not being rendered properly. Please guide how to solve this. Would like to work on it. Thanks.

This screenshot is from the Manual page.

### PR DESCRIPTION
**Pull request by sidntrivedi012**
Probably Fixes #20. @ry Please take a look. Thanks.

### CODE REVIEW

**Comment by sidntrivedi012** [comment]
According to the doc here - https://github.com/rexxars/react-markdown#options - `Be aware that setting this to false might cause security issues if the input is user-generated. Use at your own risk.` 

Will that be a problem? If yes, we can look for some alternative.

**Comment by ry** [comment]
@sidntrivedi012 Because /x/ serves unreviewed markdown, we must escape the HTML for security.

**Comment by sidntrivedi012** [comment]
@ry we can parse html according to our needs. - Like for instance, they have mentioned here - https://github.com/rexxars/react-markdown#parsing-html

We can make add required nodes here  -

**Comment by ry** [comment]
@sidntrivedi012 Sounds good to me!

**Comment by sidntrivedi012** [comment]
@ry, Added the check condition for parsing HTML. It declares a node as invalid if it has the `script` tag. PTAL. Thanks.

**Comment by ry** [comment]
Cool - is disallowing script the only thing we need to be worried of? What about iframe or canvas ? Also please run “npm run format”

**Comment by ry** [comment]
I will land your commit in https://github.com/denoland/deno_website2/pull/36 - thanks!

**Comment by sidntrivedi012** [comment]
Sure, thanks. Working on filtering iframe as well as canvas. Will make a PR if I figure out how to get it done. 🙂

**Pull request closed without merging**
