### PR TITLE
Persist line break in code blocks

### LINKED ISSUE #466: Copying code snippets does not include spacing so gets removed when pasted
Copy:
Screenshot 2020-05-14 at 23 14 22

Paste:
Screenshot 2020-05-14 at 23 15 53

### PR DESCRIPTION
**Pull request by kidonng**
Fix #466
Also hide blank line at the end of file.

### CODE REVIEW

**Comment by lucacasonato** [comment]
Would this still work for lines that are actually just one long? As in have just a single letter?

**Comment by kidonng** [comment]
All the following conditions are tested:

- Single blank line
  ```

  ```
- Two blank line
  ```

  ```
- Single line code
  ```
  console.log('hello world')
  ```
- Single char
  ```
  ;
  ```

---

I also hide the blank line at the end of the file if it exists.

**Comment by ry** [comment]
I don't understand what this does...

**Comment by kidonng** [comment]
@ry line break (enter) isn't presented in code blocks, they will be left out if you copy and paste them elsewhere. See the original issue (#466) for an example

**Comment by kidonng** [comment]
> Tho this is all becoming quite complex

It looks like that because there are extra logic checking if it's a blank line at the end of the file.

But thanks for reminding me, I just noticed another bug caused by me 😅 sorry. Working on a fix.

**Comment by lucacasonato** [comment]
I think this is the cause of #601

**Pull request merged**
