### PR TITLE
Add is-promise npm package

### PR DESCRIPTION
**Pull request by ForbesLindesay**
It can currently be used in deno via:

```js
import isPromise from 'https://unpkg.com/is-promise@4.0.0/index.mjs';

if (isPromise({then: () => {}})) {
  console.log('it is a promise');
} else {
  console.log('it is not a promise');
}
```

I'm not sure if there's anything else I should be doing to properly support deno.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
@ry is that an intentional choice not to allow `-` in the module name? It seems like that's quite a significant restriction for people moving from node.

**Comment by lucacasonato** [comment]
Yes that is an intentional choice

**Comment by ry** [comment]
Closing because red. Start a new PR if you want to get this in.

**Comment by ForbesLindesay** [comment]
Given that you do not support `-` in package names, I don't really see a path forwards here. In addition, the number of people who simply down-voted the PR, leads me to conclude that deno is a toxic community. I will not be supporting deno in my packages for the foreseeable future. I do sincerely hope both problems can be fixed, as there's a lot to like about deno.

**Comment by nayeemrmn** [comment]
@ForbesLindesay I didn't down-vote but to provide context, the recent history of your package renewed a sentiment amongst the community that Deno would be a chance to address some problems with the existing ecosystem, particularly discouraging trivial dependencies.

Maybe it will, maybe it won't. But down-voting packages like this is unfortunately the only way people have of steering towards the first case.

I agree about `-` given that we have an `"npm"` type. I disagree that the community is toxic for simply down-voting 🤷‍♂️

**Comment by Pointotech** [comment]
In which world is `-` not a valid URL character? It's literally the only idiomatic way to separate words in a URL. This is a really weird decision to make, especially without justifying it, and especially in an ecosystem like Deno where ALL PACKAGES are loaded from URLs.

Why is the Deno community attempting to get rid of the harmless dash character, and slow down interop/migration from Node for no apparent reason?

**Comment by Soremwar** [comment]
@Pointotech By definition `-` isn't an alphanumeric character. `_` is.

**Comment by lucacasonato** [comment]
@Pointotech We allow only a single separator character (`-`). This is to avoid many modules having a similar name: e.g. `is_even` and `is-even`. The decision was made over a year ago, and won't me changed. If you don't like deno.land/x because of this, host your packages somewhere else. The beauty of standard URL imports is that you are not forced to use any specific registry like deno.land/x :-)

**Comment by andreespirela** [comment]
@ForbesLindesay not that it's relevant, but I hardly disagree with your statement:  
> leads me to conclude that deno is a toxic community
You should really give it a try to our Discord chat.

**Comment by Pointotech** [comment]
That last comment is hardly fair, though. Every Discord chat is a toxic mess, because of Discord.

**Pull request closed without merging**
