### PR TITLE
Added DenoChalk

### PR DESCRIPTION
**Pull request by AvexCodes**
Added my module.

### CODE REVIEW

**Comment by SkoshRG** [comment]
I suggest you check that the json you are trying to merge is valid, which in this commit isn't the case.


"deno_chalk": {
    "type": "github",
    "owner": "avexcodes",
    "repo": "denochalk",
    "desc": "Allows you to add colour, and styling to your console!"
},

This is what the object should be like. Also, I'm not sure what benefit this package adds? It seems quite exactly the same as the implementation in Deno's built in color formatting options, but with a less scalable API.

**Comment by crowlKats** [comment]
duplicate PR? #256

**Comment by kitsonk** [comment]
Also isn't it redundant with: https://github.com/denoland/deno/blob/master/std/fmt/colors.ts

**Comment by ry** [comment]
stale

**Pull request closed without merging**
