### PR TITLE
Remove duplicate entries from database.json

### PR DESCRIPTION
**Pull request by garronej**

### CODE REVIEW

**Comment by lucacasonato** [comment]
Can you please retrigger the CI by sending an creating an empty commit? `git commit -m "Retrigger CI" --allow-empty`

**Comment by garronej** [comment]
sure thing

**Comment by parzhitsky** [comment]
Perhaps, would make sense to turn `database.json` into a large default-exported object in `database.ts`, and rip the benefits of type checking?

**Comment by garronej** [comment]
> Perhaps, would make sense to turn `database.json` into a large default-exported object in `database.ts`, and rip the benefits of type checking?

Well... I am just about done working on a CI tool that assists people in publishing Deno module [denoify_ci](https://github.com/garronej/denoify_ci). If you make this change that would mean that I have to rewrite the script that automates the submission of a PR to edit database.json.   

It is not really your problem I know but I just mention it.

**Comment by parzhitsky** [comment]
> script that automates the submission of a PR to edit database.json

Could you point me to that one? I couldn't find it

**Comment by garronej** [comment]
> > script that automates the submission of a PR to edit database.json
> 
> Could you point me to that one? I couldn't find it

Yes thanks: https://github.com/garronej/github_actions_toolkit/blob/master/src/submit_module_on_deno_land.ts

**Comment by parzhitsky** [comment]
Just to be clear, I'm not affiliated with deno team, just another contributor

**Comment by garronej** [comment]
> It wouldn't require too much work to rewrite, IMO. Consider the approach of literally adding lines to the file.
> 
> Anyway, this has to be implemented first, and I doubt that it will pass the review 😄
> 
> P.S.: Just to be clear, I'm not affiliated with deno team, just another contributor

Agree

**Pull request merged**
