### PR TITLE
feat: file search

### PR DESCRIPTION
**Pull request by lucacasonato**
You can now search an entire directory / module recursively for filenames. The shortcut to select the search bar is `t`. This is the same as on GitHub.

### CODE REVIEW

**Comment by ry** [comment]
Cool! Why 't'? 

I would think '/' makes more sense. In docs.rs they use 'S' (always seemed odd to me)

**Comment by lucacasonato** [comment]
> Why 't'?

It is the hotkey on GitHub so I thought people would be familiar with it. I can change it to `/` though.

**Comment by SyrupThinker** [comment]
> It is the hotkey on GitHub

It's *a* hotkey (:
The slash on the search button says which one they expected to be used :D

Why not both?

**Comment by ry** [comment]
Oh I didn't know about that feature on github. That makes sense. I'm ok with 't'.

**Comment by lucacasonato** [comment]
> The slash on the search button says which one they expected to be used :D
>
> Why not both?

The `/` is for the full repo search in the top left. `t` is for what GitHub calls the `file finder`

**Comment by SyrupThinker** [comment]
Weird, my buttons must be messed up, s opens the file finder for me :p
Ignore me then

**Pull request merged**
